conceptos_map = {
    "activo": "Activo",
    "activo_corto_plazo": "Activo a corto plazo",
    "caja": "Caja",
    "caja_efectivo": "Caja efectivo",
    "bancos": "Bancos",
    "inversiones": "Inversiones",
    "inversiones_temporales": "Inversiones temporales",
    "clientes": "Clientes",
    "clientes_nacionales": "Clientes nacionales",
    "cuentas_documentos_por_cobrar_corto_plazo": "Cuentas y documentos por cobrar a corto plazo",
    "cuentas_documentos_por_cobrar_corto_plazo_nacional": "Cuentas y documentos por a cobrar corto plazo nacional",
    "deudores_diversos": "Deudores diversos",
    "funcionarios_empleados": "Funcionarios y empleados",
    "otros_deudores_diversos": "Otros deudores diversos",
    "estimacion_cuentas_incobrables": "Estimación de cuentas incobrables",
    "pagos_anticipados": "Pagos anticipados",
    "seguros_finanzas_pagados_anticipado_nacional": "Seguros y finanzas pagados por anticipado nacional",
    "rentas_pagados_anticipado_nacional": "Rentas pagados anticipado nacional",
    "inventario": "Inventario",
    "materia_prima_materiales": "Materia prima y materiales",
    "produccion_en_proceso": "Producción en proceso",
    "anticipo_proveedores": "Anticipo a aproveedores",
    "anticipo_proveedores_nacional": "Anticipo a aproveedores nacional",
    "otros_activos_corto_plazo": "Otros activos a corto plazo",
    "terreno": "Terreno",
    "edificios": "Edificios",
    "maquinas_equipos": "Máquinas y equipos",
    "autos_camiones": "Autos y camiones",
    "mobiliario_equipo_oficina": "Mobiliario y equipo oficina",
    "equipo_computo": "Equipo de computo",
    "equipo_comunicacion": "Equipo de comunicación",
    "otros_activos_fijos": "Otros activos fijos",
    "gastos_diferidos": "Gastos diferidos",
    "activos_intangibles": "Activos intangibles",
    "gastos_organizacion": "Gastos de organización",
    "gastos_instalacion": "Gastos de instalación",
    "cuentas_documentos_por_cobrar_largo_plazo": "Cuentas y documentos por cobrar largo plazo",
    "cuentas_documentos_por_cobrar_largo_plazo_nacional": "Cuentas y documentos por cobrar largo plazo nacional",
    "pasivo": "Pasivo",
    "pasivo_corto_plazo": "Pasivo a corto plazo",
    "proveedores": "Proveedores",
    "cuentas_por_pagar_corto_plazo": "Cuentas por pagar a corto plazo",
    "documento_por_pagar_bancario": "Documento por pagar bancario",
    "cobros_anticipados_corto_plazo": "Cobros anticipados a corto plazo",
    "rentas_cobradas_anticipado_corto_plazo_nacional": "Rentas cobradas por anticipado a corto plazo nacional",
    "impuestos_traslados": "Impuestos traslados",
    "iva_traslado": "IVA traslado",
    "otros_pasivos_corto_plazo": "Otros pasivos a corto plazo",
    "pasivo_largo_plazo": "Pasivo a largo plazo",
    "acreedores_diversos_largo_plazo": "Acreedores diversos a largo plazo",
    "cuentas_por_pagar_largo_plazo": "Cuentas por pagar a largo plazo",
    "documentos_bancarios_financieros_por_pagar_largo_plazo_nacional": "Documentos bancarios y financieros por pagar largo plazo nacional",
    "capital_contable": "Capital contable",
    "capital_social": "Capital social",
    "capital_fijo": "Capital fijo",
    "capital_variable": "Capital variable",
    "patrimonio": "Patrimonio",
    "aportacion_patrimonial": "Aportación patrimonial",
    "reserva_legal": "Reserva legal",
    "resultado_ejercicios_anteriores": "Resultado de ejercicios anteriores",
    "utilidad_ejercicios_anteriores": "Utilidad de ejercicios anteriores",
    "perdidas_ejercicios_anteriores": "Pérdidas de ejercicios anteriores",
    "resultado_integral_ejercicios_anteriores": "Resultado integral de ejercicios anteriores",
    "resultado_ejercicio": "Resultado ejercicio",
    "utilidad_ejecicio": "Utilidad ejercicio",
    "perida_ejercicio": "Pérdida ejercicio",
}

agrupaciones = {
    "Activo": [
        "activo",
        "activo_corto_plazo",
        "caja",
        "caja_efectivo",
        "bancos",
        "inversiones",
        "inversiones_temporales",
        "clientes",
        "clientes_nacionales",
        "cuentas_documentos_por_cobrar_corto_plazo",
        "cuentas_documentos_por_cobrar_corto_plazo_nacional",
        "deudores_diversos",
        "funcionarios_empleados",
        "otros_deudores_diversos",
        "estimacion_cuentas_incobrables",
        "pagos_anticipados",
        "seguros_finanzas_pagados_anticipado_nacional",
        "rentas_pagados_anticipado_nacional",
        "inventario",
        "materia_prima_materiales",
        "produccion_en_proceso",
        "anticipo_proveedores",
        "anticipo_proveedores_nacional",
        "otros_activos_corto_plazo",
        "terreno",
        "edificios",
        "maquinas_equipos",
        "autos_camiones",
        "mobiliario_equipo_oficina",
        "equipo_computo",
        "equipo_comunicacion",
        "otros_activos_fijos",
        "cuentas_documentos_por_cobrar_largo_plazo",
        "cuentas_documentos_por_cobrar_largo_plazo_nacional",
        "gastos_diferidos",
        "activos_intangibles",
        "gastos_organizacion",
        "gastos_instalacion",
    ],
    "Pasivo": [
        "pasivo",
        "pasivo_corto_plazo",
        "proveedores",
        "cuentas_por_pagar_corto_plazo",
        "documento_por_pagar_bancario",
        "cobros_anticipados_corto_plazo",
        "rentas_cobradas_anticipado_corto_plazo_nacional",
        "impuestos_traslados",
        "iva_traslado",
        "otros_pasivos_corto_plazo",
        "pasivo_largo_plazo",
        "acreedores_diversos_largo_plazo",
        "cuentas_por_pagar_largo_plazo",
        "documentos_bancarios_financieros_por_pagar_largo_plazo_nacional",
    ],
    "Capital contable": [
        "capital_contable",
        "capital_social",
        "capital_fijo",
        "capital_variable",
        "patrimonio",
        "aportacion_patrimonial",
        "reserva_legal",
        "resultado_ejercicios_anteriores",
        "utilidad_ejercicios_anteriores",
        "perdidas_ejercicios_anteriores",
        "resultado_integral_ejercicios_anteriores",
        "resultado_ejercicio",
        "utilidad_ejecicio",
        "perida_ejercicio",
    ],
}
