version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongo_finance
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: finance_db
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro

volumes:
  mongo_data:
