from apps.mongo.core.base_mongo_model import BaseMongoModel, mongo_model
from apps.tools.objectid import ObjectId


@mongo_model(collection_name="estado_resultados", schema_version=1)
class EstadoResultados(BaseMongoModel):
    id_periodo: ObjectId
    activo: float
    activo_corto_plazo: float
    caja: float
    caja_efectivo: float
    bancos: float
    inversiones: float
    inversiones_temporales: float
    clientes: float
    clientes_nacionales: float
    cuentas_documentos_por_cobrar_corto_plazo: float
    cuentas_documentos_por_cobrar_corto_plazo_nacional: float
    deudores_diversos: float
    funcionarios_empleados: float
    otros_deudores_diversos: float
    estimacion_cuentas_incobrables: float
    pagos_anticipados: float
    seguros_finanzas_pagados_anticipado_nacional: float
    rentas_pagados_anticipado_nacional: float
    inventario: float
    materia_prima_materiales: float
    produccion_en_proceso: float
    anticipo_proveedores: float
    anticipo_proveedores_nacional: float
    otros_activos_corto_plazo: float
    activo_corto_plazo: float
    terreno: float
    edificios: float
    maquinas_equipos: float
    autos_camiones: float
    mobiliario_equipo_oficina: float
    equipo_computo: float
    equipo_comunicacion: float
    otros_activos_fijos: float
    gastos_diferidos: float
    activos_intangibles: float
    gastos_organizacion: float
    gastos_instalacion: float
    cuentas_documentos_por_cobrar_largo_plazo: float
    cuentas_documentos_por_cobrar_largo_plazo_nacional: float
    pasivo: float
    pasivo_corto_plazo: float
    proveedores: float
    cuentas_por_pagar_corto_plazo: float
    documento_por_pagar_bancario: float
    cobros_anticipados_corto_plazo: float
    rentas_cobradas_anticipado_corto_plazo_nacional: float
    impuestos_traslados: float
    iva_traslado: float
    otros_pasivos_corto_plazo: float
    pasivo_largo_plazo: float
    acreedores_diversos_largo_plazo: float
    cuentas_por_pagar_largo_plazo: float
    documentos_bancarios_financieros_por_pagar_largo_plazo_nacional: float
    capital_contable: float
    capital_social: float
    capital_fijo: float
    capital_variable: float
    patrimonio: float
    aportacion_patrimonial: float
    reserva_legal: float
    resultado_ejercicios_anteriores: float
    utilidad_ejercicios_anteriores: float
    perdidas_ejercicios_anteriores: float
    resultado_integral_ejercicios_anteriores: float
    resultado_ejercicio: float
    utilidad_ejecicio: float
    perida_ejercicio: float
